### ISSUE TITLE
не работает через иконку в шторке

### ISSUE THREAD

**Issue by Frech4k** [dovecoteescapee/ByeDPIAndroid#47]
когда нажимаю на иконку эту, пишет, что приложение недоступно, как, например, у впн от гугл, потом вылазит уведомление, что в приложение данном произошел сбой 
A14

**Comment by kaajjo** [comment]
Logs:
```
Process: io.github.dovecoteescapee.byedpi, PID: 8724
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=start cmp=io.github.dovecoteescapee.byedpi/.services.ByeDpiVpnService }:
app is in background uid UidRecord{3f92880 u0a198 CEM  bg:+339ms idle change:cached|procstate|procadj procs:0 seq(25598,25598)} caps=-------
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1973)
at android.app.ContextImpl.startService(ContextImpl.java:1928)
at android.content.ContextWrapper.startService(ContextWrapper.java:827)
at io.github.dovecoteescapee.byedpi.services.ServiceManager.start(ServiceManager.kt:19)
at io.github.dovecoteescapee.byedpi.services.QuickTileService.handleClick(QuickTileService.kt:127)
at io.github.dovecoteescapee.byedpi.services.QuickTileService.$r8$lambda$AdhcN-uJGaWWeTmistv3bEvdKCk(Unknown Source:0)
at io.github.dovecoteescapee.byedpi.services.QuickTileService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
at android.service.quicksettings.TileService$H.handleMessage(TileService.java:499)
```

**Comment by amikhailov-png** [comment]
При запуске версии 1.0.2-rc1 отваливается Samsung Smart View (screen mirroring) с сообщением "Соединение с телевизором разорвано из-за запуска VPN".

Версия 1.0.1 работала без сбоев.
